---
- name: Checkout dlrnapi_client
  git:
    repo: '{{ dlrnapi_client_repo }}'
    dest: /tmp/dlrnapi_client
    update: yes
    force: yes
    version: '{{ dlrnapi_client_version }}'

- name: Install dlrnapi_client
  pip:
    executable: '{{ pip_executable }}'
    name: file:///tmp/dlrnapi_client
    extra_args: --user

- name: Set dlrnapi_client executable variable
  set_fact:
    dlrnapi: '{{ ansible_user_dir }}/.local/bin/dlrnapi'
