---
- name: Checkout DLRN
  git:
    repo: '{{ dlrn_repo }}'
    dest: /tmp/DLRN
    update: yes
    force: yes
    version: '{{ dlrn_version }}'

- name: Install DLRN
  pip:
    executable: '{{ pip_executable }}'
    name: file:///tmp/DLRN
    extra_args: --user

- name: Set DLRN executable variable
  set_fact:
    dlrn: '{{ ansible_user_dir }}/.local/bin/dlrn'
