---
- name: Check for dlrn installed
  command: bash -c "type dlrn"
  ignore_errors: yes
  failed_when: dlrn_exists.rc not in [0, 1]
  register: dlrn_exists

- name: Try to install via RPM
  package:
    name: rh-python35-dlrn
    state: present
  ignore_errors: true
  failed_when: pkg_present.rc not in [0, 1]
  become: true
  register: pkg_present
  when: dlrn_exists is failed

#TODO: Maybe better to install it in a virtualenv ?
- name: Install using pip if yum fails
  pip:
    name: dlrn
  when:
    - pkg_present is failed
    - dlrn_exists is failed
