---
- name: Checkout rdopkg
  git:
    repo: '{{ rdopkg_repo }}'
    dest: /tmp/rdopkg
    update: yes
    force: yes
    version: '{{ rdopkg_version }}'

- name: Install rdopkg
  pip:
    executable: '{{ pip_executable }}'
    name: file:///tmp/rdopkg
    extra_args: --user

- name: Set rdopkg executable variable
  set_fact:
    rdopkg: '{{ ansible_user_dir }}/.local/bin/rdopkg'
