---
- name: Delete data directory if exist
  file:
    path: "{{ dlrn_data }}"
    state: absent

- name: Create data directory
  file:
    path: "{{ dlrn_data }}"
    state: directory

- name: Copy target mock cfg
  copy:
    src: "{{ ansible_user_dir }}/{{ dlrn_project }}.cfg"
    dest: "{{ working_dir }}/{{ dlrn_project }}.cfg"
    remote_src: true

- name: Set project.ini values according to current config
  template:
    src: "projects.ini.j2"
    dest: "{{ working_dir }}/projects.ini"

- name: Clean previous commits.sqlite
  file:
    path: "{{ working_dir }}/commits.sqlite"
    state: absent

- name: Run DLRN build
  command: >
    {{ dlrn }} --config-file {{ working_dir }}/projects.ini
         --verbose-build
  args:
    chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
  ignore_errors: yes
  register: dlrnbuild

- name: Make sure current link is set
  shell:
    cmd: "test -L current || ln -s $(dirname $(find . -name commit.yaml)) current"
  args:
    chdir: "{{ dlrn_data }}/repos"

- name: Fail under context conditions
  fail:
    msg: "DLRN build failed"
  when: dlrnbuild.rc != 0
